site_name: ChatOL 文档
site_url: https://arch.gh.wzhecnu.cn/ChatOL/
repo_url: https://github.com/ChatArch/ChatOL
theme:
  name: material
  language: zh
nav:
  - 首页: index.md
  - 开发计划: development-plan.md
  - 真实实践: live-practice.md
  - English: index.en.md
